baseURL: ""
defaultContentLanguageInSubdir: true
defaultContentLanguage: "en"
title: "LOCD Learning on your own!"
pluralizelisttitles: "false"
relativeURLs: "true"
publishDir: "../build"
layout: "bundle"

languages:
  gb:
    languageName: English
    weight: 1
    contentDir: "content/en"

  fr:
    languageName: Fran√ßais
    weight: 2
    contentDir: "content/fr"

  nl:
    languageName: Nederlands
    weight: 3
    contentDir: "content/nl"

disableKinds: ["taxonomy", "taxonomyTerm", "section"]

markup:
  goldmark:
    renderer:
      unsafe: true
# sectionPagesMenu: "main"

# menu:
#   main:
#   - identifier: HTML5
#     name: HTML5
#     title: HTML5
#     url: /html/
#     weight: 1

#   - identifier: Css-start
#     name: Css-start
#     title: Css-start
#     url: /css/
#     weight: 4
